import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import data from "../dummydata/data.json";
import { converttoarr } from "./functions/converttoarr";
import Navbar from "./components/Navbar/Navbar";
import Blogbody from "./components/Blogbody";
import Footer from "./components/Footer";

export default function Home() {
  const [dd, setdd] = useState([]);
  useEffect(() => {
    const arr = converttoarr(data);

    setdd(arr);
  }, []);

  return (
    <div>
      <Head>
        <title>Blog Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navbar}>
        <Navbar />
      </div>
      <div>
        <Blogbody />
      </div>
      <div>
        <Footer />
      </div>
    </div>
  );
}
