import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import data from "../dummydata/data.json";
import { converttoarr } from "./functions/converttoarr";
import Navbar from "./components/Navbar/Navbar";
import Blogbody from "./components/Blogbody/Blogbody";
import Footer from "./components/Footer";

export default function Home({ db }) {
  useEffect(() => {}, []);
  return (
    <div>
      <Head>
        <title>Blog Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navbar}>
        <Navbar />
      </div>
      <div>
        <Blogbody db={converttoarr(db)} />
      </div>
      <div>
        <Footer />
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const arr = converttoarr(data);
  return {
    props: {
      db: data,
    },
  };
}
